 ## Exercises XP: W3_D1

#### Exercise 1: Array Creation and Manipulation

In [2]:
# Import the NumPy library
import numpy as np

# Create a 1D NumPy array containing numbers from 0 to 9
array_1d = np.arange(10)

# Display the result
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise 2: Type Conversion and Array Operations

In [10]:
# Define a Python list with float and integer values
my_list = [3.14, 2.17, 0, 1, 2]

# Convert the list to a NumPy array with integer data type
int_array = np.array(my_list, dtype=int)

# Display the result
print(int_array)

[3 2 0 1 2]


#### Exercise 3: Working with Multi-Dimensional Arrays

In [9]:
# Create a 1D array with values from 1 to 9
array_1d = np.arange(1, 10)

# Reshape the 1D array into a 3x3 2D array
array_2d = array_1d.reshape((3, 3))

# Display the result
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Exercise 4: Creating Multi-Dimensional Array with Random Numbers

In [8]:
# Create a 2D array of shape (4, 5) filled with random floats between 0 and 1
random_array = np.random.rand(4, 5)

# Round the numbers to 2 decimal places for readability
random_array = np.round(random_array, 2)

# Display the result
print(random_array)

[[0.69 0.75 0.28 0.87 0.21]
 [0.65 0.13 0.29 0.41 0.01]
 [0.79 0.03 0.35 0.22 0.21]
 [0.84 0.76 0.98 0.55 0.97]]


#### Exercise 5: Indexing Arrays

In [7]:
# Define a 2D NumPy array
array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

# Select the second row (index 1, because indexing starts at 0)
second_row = array[1]

# Display the result
print(second_row)

[20 21 22 23 24]


#### Exercise 6: Reversing Elements

In [12]:
# Create a 1D array with values from 0 to 9
array = np.arange(10)

# Reverse the array using slicing
reversed_array = array[::-1]

# Display the result
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


#### Exercise 7: Identity Matrix

In [13]:
# Create a 4x4 identity matrix
identity_matrix = np.eye(4)

# Display the result
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Exercise 8: Simple Aggregate Functions

In [15]:
# Create a 1D array with values from 0 to 9
array = np.arange(10)

# Calculate the sum of the array elements
array_sum = np.sum(array)

# Calculate the average (mean) of the array elements
array_mean = np.mean(array)

# Display the results
print("Sum:", array_sum)
print("Average:", array_mean)

Sum: 45
Average: 4.5


#### Exercise 9: Create Array and Change its Structure

In [16]:
# Create a 1D array with values from 1 to 20
array = np.arange(1, 21)

# Reshape the array into a 4x5 matrix
reshaped_array = array.reshape((4, 5))

# Display the result
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### Exercise 10: Conditional Selection of Values

In [17]:
# Create a 1D array with values from 0 to 9
array = np.arange(10)

# Select only the odd numbers using a boolean condition
odd_numbers = array[array % 2 == 1]

# Display the result
print(odd_numbers)

[1 3 5 7 9]
