# Exercises XP Ninja: W3_D1

## What You’ll Learn
- How to manipulate matrices and identify commonalities in datasets using NumPy.
- Advanced array operations such as maximum value replacement and finding common values.
- Sorting arrays in ascending and descending order.
- Determining matrix rank and creating structured arrays.

## What You’ll Create
- A 5×5 matrix with its maximum value replaced by 0.
- Identification of common values between two arrays.
- Sorted arrays (ascending & descending).
- A random 4×4 matrix with rank calculation.
- A 2D border array with 1s on the edges and 0s inside.

---

## Exercises

**Exercise 1 — Maximum Value Replacement in Matrix**  
Create a random 5×5 matrix and replace its maximum value with 0.

**Exercise 2 — Finding Common Values in Arrays**  
Find the common values between two random arrays of size 5.

**Exercise 3 — Sorting Array in Ascending and Descending Order**  
Create a random 1D array of size 10 and sort it in ascending and descending order.

**Exercise 4 — Matrix Rank Determination**  
Generate a random 4×4 matrix and determine its rank.

**Exercise 5 — Creating Border Array**  
Create a 2D array with 1s on the border and 0s inside.

## Setup — Imports and Random Seed

In [1]:
# Goal: Import NumPy and set a seed for reproducibility.

import numpy as np
np.random.seed(42)

## Exercise 1 : Maximum Value Replacement in Matrix

In [2]:
# Title: Exercise 1 — Replace Matrix Maximum with 0
# Task: Create a random 5x5 matrix and replace its maximum value(s) by 0.

A = np.random.rand(5, 5)  # values in [0,1)
print("Original 5x5 matrix:\n", np.round(A, 2))

# Find the maximum and replace *all* occurrences with 0 (handles potential ties safely)
max_val = A.max()
A[A == max_val] = 0.0

print("\nAfter replacing max value(s) with 0:\n", np.round(A, 2))

Original 5x5 matrix:
 [[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]

After replacing max value(s) with 0:
 [[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.   0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]


## Exercise 2 : Finding Common Values in Arrays

In [3]:
# Title: Exercise 2 — Common Values Between Two Arrays
# Task: Find common values between two random arrays of size 5.

x = np.random.rand(5)
y = np.random.rand(5)

print("x:", np.round(x, 3))
print("y:", np.round(y, 3))

# Method A: Exact intersection (works for integers or identical floats)
exact_common = np.intersect1d(x, y)
print("\nExact common values:", exact_common)

# Method B: Float-friendly intersection using rounding (e.g., 2 decimals)
# Rationale: pure random floats rarely match exactly; rounding groups close values.
x2 = np.round(x, 2)
y2 = np.round(y, 2)
common_2dp = np.intersect1d(x2, y2)

print("Common values (rounded to 2 decimals):", common_2dp)

x: [0.785 0.2   0.514 0.592 0.046]
y: [0.608 0.171 0.065 0.949 0.966]

Exact common values: []
Common values (rounded to 2 decimals): []


## Exercise 3 : Sorting Array in Ascending and Descending Order

In [4]:
# Title: Exercise 3 — Sort 1D Array (Ascending & Descending)
# Task: Create a random 1D array of size 10 and sort it both ways.

arr = np.random.rand(10)

asc = np.sort(arr)                # ascending
desc = np.sort(arr)[::-1]         # descending

print("Original:", np.round(arr, 3))
print("Ascending:", np.round(asc, 3))
print("Descending:", np.round(desc, 3))

Original: [0.808 0.305 0.098 0.684 0.44  0.122 0.495 0.034 0.909 0.259]
Ascending: [0.034 0.098 0.122 0.259 0.305 0.44  0.495 0.684 0.808 0.909]
Descending: [0.909 0.808 0.684 0.495 0.44  0.305 0.259 0.122 0.098 0.034]


## Exercise 4 : Matrix Rank Determination

In [5]:
# Title: Exercise 4 — Compute Matrix Rank
# Task: Generate a random 4x4 matrix and find its rank.

M = np.random.randn(4, 4)  # standard normal entries
rank = np.linalg.matrix_rank(M)

print("Matrix (rounded):\n", np.round(M, 3))
print("\nRank:", rank)

Matrix (rounded):
 [[-1.265  1.092  2.778  1.194]
 [ 0.219  0.882 -1.009 -1.583]
 [ 0.774 -0.538 -1.347 -0.881]
 [-1.131  0.134  0.582  0.888]]

Rank: 4


## Exercise 5 : Creating Border Array

In [6]:
# Title: Exercise 5 — 2D Array with 1s on the Border and 0s Inside
# Task: Create a 5x5 array with border=1 and interior=0.

border = np.ones((5, 5), dtype=int)
border[1:-1, 1:-1] = 0

print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Conclusion & Key Takeaways — Exercises XP Ninja (NumPy)

### Exercise 1 — Maximum Value Replacement
- Generated a 5×5 random matrix and identified its maximum value.
- Replaced all occurrences of this maximum value with 0.
- Useful for **outlier handling** or flagging extreme values.

---

### Exercise 2 — Finding Common Values in Arrays
- Compared two arrays to find shared values.
- Highlighted the challenge of **exact float matching** — often requires rounding for practical matches.
- Useful in **data merging**, **set operations**, or identifying **shared attributes**.

---

### Exercise 3 — Sorting Arrays
- Sorted a 1D array in **ascending** and **descending** order.
- Reinforced that `np.sort()` returns ascending by default, and reversing (`[::-1]`) achieves descending.
- Sorting is key for **ranking**, **thresholding**, and **ordered analysis**.

---

### Exercise 4 — Matrix Rank
- Generated a 4×4 random matrix and computed its **rank** with `np.linalg.matrix_rank`.
- Rank measures the number of **linearly independent** rows/columns.
- Important in **linear algebra**, **system solvability**, and **dimensionality reduction**.

---

### Exercise 5 — Border Array
- Created a structured array with **1s on the border** and **0s inside**.
- Demonstrated index slicing to target specific array regions.
- Similar logic is used in **image processing** (mask creation, padding).

---

### Overall Reflections
- These exercises reinforce **core NumPy skills**:
  - Array creation and modification.
  - Index-based assignment.
  - Set operations and value matching.
  - Sorting and ranking.
  - Linear algebra functions.
- Mastery of these basics is essential for **data preprocessing**, **matrix computations**, and **algorithmic implementations**.

> **Next Steps:**  
> - Explore boolean indexing for complex replacement rules.  
> - Work with higher-dimensional arrays.  
> - Apply rank concepts in solving real systems of equations.