# Exercises XP Gold: W3_D1

## What You’ll Learn
- Advanced NumPy techniques for random arrays, matrix normalization, and evenly spaced arrays.
- Finding minimum/maximum and performing matrix normalization.
- Valid matrix multiplication with compatible dimensions.

## What You’ll Create
- A 5×5 array with random values and its min/max.
- A normalized 3×3 matrix (zero mean, unit std).
- A 1D array of evenly spaced elements.
- Valid matrix multiplications (5×3)·(3×2) and a custom example.

> Notes  
> - Randomness is seeded for reproducibility.  
> - For normalization: `Z = (X - X.mean()) / X.std()`  
> - Matrix multiplication uses `@` (same as `np.dot`).

## Setup — Imports and Random Seed

In [1]:
# Goal: Import NumPy and set a seed for reproducibility.

import numpy as np

np.random.seed(42)  # reproducible random numbers

## Exercise 1 : Minimum and Maximum of Random Array

In [2]:
# Task: Create a 5x5 array with random values and print its min and max.

# Option A: Default uniform [0, 1)
arr_5x5 = np.random.rand(5, 5)
print("Array (5x5):\n", arr_5x5)

print("\nMin (default [0,1)):", arr_5x5.min())
print("Max (default [0,1)):", arr_5x5.max())

# Option B (optional): Scale to [0.01, 0.99] to match the style of the expected output
scaled = 0.01 + arr_5x5 * (0.99 - 0.01)
print("\nScaled to [0.01, 0.99] — Min/Max:")
print("Min:", scaled.min())
print("Max:", scaled.max())

Array (5x5):
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Min (default [0,1)): 0.020584494295802447
Max (default [0,1)): 0.9699098521619943

Scaled to [0.01, 0.99] — Min/Max:
Min: 0.0301728044098864
Max: 0.9605116551187545


## Exercise 2 : Matrix Normalization

In [3]:
# Task: Create a 3x3 random matrix; subtract mean and divide by std so that mean≈0 and std≈1.

X = np.random.randn(3, 3)  # standard normal entries
mu = X.mean()
sigma = X.std(ddof=0)      # population std; ddof=0 is fine for normalization

Z = (X - mu) / sigma

print("Original 3x3 matrix X:\n", X)
print("\nMean(X):", mu, "  Std(X):", sigma)
print("\nNormalized matrix Z = (X - mean)/std:\n", Z)

# Sanity checks
print("\nChecks on Z (numerical, may not be exactly 0/1 due to rounding):")
print("Mean(Z) ≈", Z.mean())
print("Std(Z)  ≈", Z.std(ddof=0))

Original 3x3 matrix X:
 [[-0.62947496  0.59772047  2.55948803]
 [ 0.39423302  0.12221917 -0.51543566]
 [-0.60025385  0.94743982  0.291034  ]]

Mean(X): 0.3518855593598763   Std(X): 0.9409661260083042

Normalized matrix Z = (X - mean)/std:
 [[-1.04292864  0.26125798  2.34610196]
 [ 0.04500424 -0.24407509 -0.9217348 ]
 [-1.01187427  0.63291785 -0.06466923]]

Checks on Z (numerical, may not be exactly 0/1 due to rounding):
Mean(Z) ≈ -6.32210333467103e-17
Std(Z)  ≈ 1.0


## Exercise 3 : Evenly Spaced Elements in Array

In [4]:
# Task: Create a 1D array of 50 evenly spaced elements between 0 and 10.

# Clarification: The prompt says "exclusive" but the example includes 10.0.
# We provide both versions:

# Inclusive endpoints [0, 10]
inclusive = np.linspace(0, 10, num=50, endpoint=True)
print("Inclusive [0, 10], 50 points:\n", inclusive)

# Exclusive of the right endpoint [0, 10)
exclusive = np.linspace(0, 10, num=50, endpoint=False)
print("\nExclusive [0, 10), 50 points:\n", exclusive)

Inclusive [0, 10], 50 points:
 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

Exclusive [0, 10), 50 points:
 [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


## Exercise 4 : Matrix Multiplication

In [5]:
# Task: Multiply a 5x3 matrix by a 3x2 matrix.

A = np.random.randint(1, 10, size=(5, 3))  # integers 1..9
B = np.random.randint(1, 10, size=(3, 2))

C = A @ B  # same as np.dot(A, B)

print("A (5x3):\n", A)
print("\nB (3x2):\n", B)
print("\nC = A @ B (5x2):\n", C)

# Shape check (defensive)
assert A.shape[1] == B.shape[0], "Incompatible shapes for matrix multiplication!"

A (5x3):
 [[7 8 3]
 [1 4 2]
 [8 4 2]
 [6 6 4]
 [6 2 2]]

B (3x2):
 [[4 8]
 [7 9]
 [8 5]]

C = A @ B (5x2):
 [[108 143]
 [ 48  54]
 [ 76 110]
 [ 98 122]
 [ 54  76]]


## Exercise 5 — Custom Matrix Multiplication

In [6]:
# Title: Exercise 5 — Custom Matrix Multiplication
# Task: Create two compatible matrices, multiply them, and display the result.

# You can change these dimensions as long as inner dims match: (m x k) @ (k x n) -> (m x n)
m, k, n = 2, 4, 3

M1 = np.arange(1, m*k + 1).reshape(m, k)      # e.g., [[1,2,3,4],[5,6,7,8]]
M2 = np.arange(1, k*n + 1).reshape(k, n)      # e.g., 4x3 matrix with increasing ints

R = M1 @ M2

print("M1 (", M1.shape, "):\n", M1)
print("\nM2 (", M2.shape, "):\n", M2)
print("\nR = M1 @ M2 (", R.shape, "):\n", R)

# Explanation (English):
# - Matrix multiplication takes the dot product of rows of M1 with columns of M2.
# - Here, shapes are (m x k) @ (k x n) -> (m x n). The inner dimension 'k' must match.

M1 ( (2, 4) ):
 [[1 2 3 4]
 [5 6 7 8]]

M2 ( (4, 3) ):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

R = M1 @ M2 ( (2, 3) ):
 [[ 70  80  90]
 [158 184 210]]


## Conclusion & Key Takeaways — Exercises XP Gold (NumPy)

### Exercise 1 — Minimum and Maximum of Random Array
- Generated a 5×5 random array from a uniform distribution in [0, 1).
- Successfully retrieved **min** and **max** values using `.min()` and `.max()`.
- Optional scaling to [0.01, 0.99] demonstrated control over random value ranges.

**Key point:** NumPy makes it easy to generate random arrays and compute descriptive statistics in one step.

---

### Exercise 2 — Matrix Normalization
- Created a 3×3 random matrix and applied normalization:
  \[
  Z = \frac{X - \text{mean}(X)}{\text{std}(X)}
  \]
- Resulting matrix has mean ≈ 0 and standard deviation ≈ 1.

**Key point:** Normalization standardizes data, making it comparable across features and preventing scale dominance in algorithms.

---

### Exercise 3 — Evenly Spaced Elements
- Generated 50 evenly spaced values using `np.linspace`.
- Covered both **inclusive** `[0, 10]` and **exclusive** `[0, 10)` cases.
- Inclusive case matches the provided example; exclusive is useful when avoiding the upper bound.

**Key point:** `np.linspace` provides control over number of points and endpoint inclusion.

---

### Exercise 4 — Matrix Multiplication (5×3)·(3×2)
- Constructed two compatible matrices and multiplied them using `@` (dot product).
- Resulting shape follows the rule: \((m \times k) @ (k \times n) \to (m \times n)\).

**Key point:** Matrix multiplication requires matching inner dimensions; the operation combines rows of the first matrix with columns of the second.

---

### Exercise 5 — Custom Matrix Multiplication
- Built custom matrices with compatible dimensions and performed multiplication.
- Showed flexibility in defining shapes and generating matrix data.
- Reinforced the requirement that **columns of the first = rows of the second**.

**Key point:** Understanding shape compatibility is essential in linear algebra, machine learning pipelines, and data transformations.

---

### Overall Reflections
- **Random number generation** + **array manipulation** + **matrix operations** = foundational NumPy skills.
- These techniques support a wide range of applications: statistics, data preprocessing, simulations, and machine learning.
- Key functions used:  
  - `np.random.rand`, `np.random.randn`, `np.random.randint`
  - `.min()`, `.max()`, `.mean()`, `.std()`
  - `np.linspace`
  - Matrix multiplication via `@` or `np.dot`

> **Next Steps:**  
> - Explore broadcasting in NumPy to avoid explicit loops.  
> - Apply normalization and multiplication in real datasets (e.g., feature scaling + transformation in ML).  
> - Experiment with higher-dimensional arrays and tensor operations.